name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ssh.ajayreddy.in
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/donkeytype/backend
            git pull
            docker stop donkeytype-backend || true
            docker rm donkeytype-backend || true
            docker build -t donkeytype-backend .
            docker run -d \
              --name donkeytype-backend \
              -p 8080:8080 \
              --restart unless-stopped \
              donkeytype-backend

